/******************************************************************************
**
** <auto-generated>
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.6.9, using .NET Server 3.3.0 template (version 0)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
** </auto-generated>
**
** Copyright (c) 2006-2023 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET OPC UA SDK information model for namespace http://yourorganisation.org/PackMLModel/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Created: 13.07.2023
**
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.Xml;
using System.Runtime.Serialization;
using UnifiedAutomation.UaBase;

namespace FIP.PackMLStateMachine
{
    #region DataType Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class DataTypes
    {
        /// <summary>
        /// The identifier for the AlarmType DataType.
        /// </summary>
        public const uint AlarmType = 3004;

        /// <summary>
        /// The identifier for the ButtonType DataType.
        /// </summary>
        public const uint ButtonType = 3005;

        /// <summary>
        /// The identifier for the ProcessType DataType.
        /// </summary>
        public const uint ProcessType = 3003;

        /// <summary>
        /// The identifier for the StackLightType DataType.
        /// </summary>
        public const uint StackLightType = 3006;

    }
    #endregion

    #region Object Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class Objects
    {
        /// <summary>
        /// The identifier for the Dictionnaries Object.
        /// </summary>
        public const uint UnitType_Dictionnaries = 5037;

        /// <summary>
        /// The identifier for the Default Binary Object.
        /// </summary>
        public const uint AlarmType_Encoding_DefaultBinary = 5001;

        /// <summary>
        /// The identifier for the Default JSON Object.
        /// </summary>
        public const uint AlarmType_Encoding_DefaultJson = 5005;

        /// <summary>
        /// The identifier for the Default XML Object.
        /// </summary>
        public const uint AlarmType_Encoding_DefaultXml = 5004;

        /// <summary>
        /// The identifier for the Default Binary Object.
        /// </summary>
        public const uint ButtonType_Encoding_DefaultBinary = 5006;

        /// <summary>
        /// The identifier for the Default JSON Object.
        /// </summary>
        public const uint ButtonType_Encoding_DefaultJson = 5008;

        /// <summary>
        /// The identifier for the Default XML Object.
        /// </summary>
        public const uint ButtonType_Encoding_DefaultXml = 5007;

        /// <summary>
        /// The identifier for the Default Binary Object.
        /// </summary>
        public const uint ProcessType_Encoding_DefaultBinary = 5002;

        /// <summary>
        /// The identifier for the Default JSON Object.
        /// </summary>
        public const uint ProcessType_Encoding_DefaultJson = 5035;

        /// <summary>
        /// The identifier for the Default XML Object.
        /// </summary>
        public const uint ProcessType_Encoding_DefaultXml = 5034;

        /// <summary>
        /// The identifier for the Default Binary Object.
        /// </summary>
        public const uint StackLightType_Encoding_DefaultBinary = 5009;

        /// <summary>
        /// The identifier for the Default JSON Object.
        /// </summary>
        public const uint StackLightType_Encoding_DefaultJson = 5011;

        /// <summary>
        /// The identifier for the Default XML Object.
        /// </summary>
        public const uint StackLightType_Encoding_DefaultXml = 5010;

        /// <summary>
        /// The identifier for the http://yourorganisation.org/PackMLModel/ Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_PackMLModel_ = 5003;

    }
    #endregion

    #region ObjectType Identifiers
    /// <summary>
    /// A class that declares constants for all ObjectTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class ObjectTypes
    {
        /// <summary>
        /// The identifier for the PackMLStateModelType ObjectType.
        /// </summary>
        public const uint PackMLStateModelType = 1005;

        /// <summary>
        /// The identifier for the UnitType ObjectType.
        /// </summary>
        public const uint UnitType = 1003;

    }
    #endregion

    #region Method Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class Methods
    {
        /// <summary>
        /// The identifier for the GetAvailableCommands Method.
        /// </summary>
        public const uint PackMLStateModelType_GetAvailableCommands = 7006;

        /// <summary>
        /// The identifier for the GetNext Method.
        /// </summary>
        public const uint PackMLStateModelType_GetNext = 7004;

        /// <summary>
        /// The identifier for the IsCommandAvailable Method.
        /// </summary>
        public const uint PackMLStateModelType_IsCommandAvailable = 7007;

        /// <summary>
        /// The identifier for the MoveNext Method.
        /// </summary>
        public const uint PackMLStateModelType_MoveNext = 7005;

        /// <summary>
        /// The identifier for the SetState Method.
        /// </summary>
        public const uint PackMLStateModelType_SetState = 7003;

        /// <summary>
        /// The identifier for the AddAlarm Method.
        /// </summary>
        public const uint UnitType_AddAlarm = 7009;

        /// <summary>
        /// The identifier for the AddAlarmsFromCSV Method.
        /// </summary>
        public const uint UnitType_AddAlarmsFromCSV = 7010;

        /// <summary>
        /// The identifier for the AddButtons Method.
        /// </summary>
        public const uint UnitType_AddButtons = 7018;

        /// <summary>
        /// The identifier for the AddButtonsFromCSV Method.
        /// </summary>
        public const uint UnitType_AddButtonsFromCSV = 7017;

        /// <summary>
        /// The identifier for the AddStackLight Method.
        /// </summary>
        public const uint UnitType_AddStackLight = 7013;

        /// <summary>
        /// The identifier for the AddStackLightsFromCSV Method.
        /// </summary>
        public const uint UnitType_AddStackLightsFromCSV = 7016;

        /// <summary>
        /// The identifier for the ExecuteProcess Method.
        /// </summary>
        public const uint UnitType_ExecuteProcess = 7026;

        /// <summary>
        /// The identifier for the ReadDataFromCSV Method.
        /// </summary>
        public const uint UnitType_ReadDataFromCSV = 7002;

        /// <summary>
        /// The identifier for the ReadDataFromDB Method.
        /// </summary>
        public const uint UnitType_ReadDataFromDB = 7025;

        /// <summary>
        /// The identifier for the RemoveAlarm Method.
        /// </summary>
        public const uint UnitType_RemoveAlarm = 7021;

        /// <summary>
        /// The identifier for the RemoveButton Method.
        /// </summary>
        public const uint UnitType_RemoveButton = 7022;

        /// <summary>
        /// The identifier for the RemoveStackLight Method.
        /// </summary>
        public const uint UnitType_RemoveStackLight = 7023;

        /// <summary>
        /// The identifier for the SafeMoveNext Method.
        /// </summary>
        public const uint UnitType_SafeMoveNext = 7008;

        /// <summary>
        /// The identifier for the SaveDataToCSV Method.
        /// </summary>
        public const uint UnitType_SaveDataToCSV = 7020;

        /// <summary>
        /// The identifier for the SaveDataToDB Method.
        /// </summary>
        public const uint UnitType_SaveDataToDB = 7024;

        /// <summary>
        /// The identifier for the SetMachineName Method.
        /// </summary>
        public const uint UnitType_SetMachineName = 7001;

        /// <summary>
        /// The identifier for the TriggerAlarm Method.
        /// </summary>
        public const uint UnitType_TriggerAlarm = 7011;

        /// <summary>
        /// The identifier for the TriggerButton Method.
        /// </summary>
        public const uint UnitType_TriggerButton = 7019;

        /// <summary>
        /// The identifier for the TriggerStackLight Method.
        /// </summary>
        public const uint UnitType_TriggerStackLight = 7014;

        /// <summary>
        /// The identifier for the UntriggerAlarm Method.
        /// </summary>
        public const uint UnitType_UntriggerAlarm = 7012;

        /// <summary>
        /// The identifier for the UntriggerStackLight Method.
        /// </summary>
        public const uint UnitType_UntriggerStackLight = 7015;

    }
    #endregion

    #region ReferenceType Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTyped in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class ReferenceTypes
    {
    }
    #endregion

    #region Variable Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class Variables
    {
        /// <summary>
        /// The identifier for the PackMLStateMachine Variable.
        /// </summary>
        public const uint OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema = 6002;

        /// <summary>
        /// The identifier for the AlarmType Variable.
        /// </summary>
        public const uint OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_AlarmType = 6004;

        /// <summary>
        /// The identifier for the ButtonType Variable.
        /// </summary>
        public const uint OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_ButtonType = 6006;

        /// <summary>
        /// The identifier for the NamespaceUri Variable.
        /// </summary>
        public const uint OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_NamespaceUri = 6003;

        /// <summary>
        /// The identifier for the ProcessType Variable.
        /// </summary>
        public const uint OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_ProcessType = 6087;

        /// <summary>
        /// The identifier for the StackLightType Variable.
        /// </summary>
        public const uint OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_StackLightType = 6007;

        /// <summary>
        /// The identifier for the PackMLStateMachine Variable.
        /// </summary>
        public const uint XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema = 6085;

        /// <summary>
        /// The identifier for the AlarmType Variable.
        /// </summary>
        public const uint XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_AlarmType = 6005;

        /// <summary>
        /// The identifier for the ButtonType Variable.
        /// </summary>
        public const uint XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_ButtonType = 6009;

        /// <summary>
        /// The identifier for the NamespaceUri Variable.
        /// </summary>
        public const uint XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_NamespaceUri = 6086;

        /// <summary>
        /// The identifier for the ProcessType Variable.
        /// </summary>
        public const uint XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_ProcessType = 6088;

        /// <summary>
        /// The identifier for the StackLightType Variable.
        /// </summary>
        public const uint XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_StackLightType = 6008;

        /// <summary>
        /// The identifier for the CurrentState Variable.
        /// </summary>
        public const uint PackMLStateModelType_CurrentState = 6084;

        /// <summary>
        /// The identifier for the OutputArguments Variable.
        /// </summary>
        public const uint PackMLStateModelType_GetAvailableCommands_OutputArguments = 6051;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint PackMLStateModelType_GetNext_InputArguments = 6050;

        /// <summary>
        /// The identifier for the OutputArguments Variable.
        /// </summary>
        public const uint PackMLStateModelType_GetNext_OutputArguments = 6053;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint PackMLStateModelType_IsCommandAvailable_InputArguments = 6055;

        /// <summary>
        /// The identifier for the OutputArguments Variable.
        /// </summary>
        public const uint PackMLStateModelType_IsCommandAvailable_OutputArguments = 6054;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint PackMLStateModelType_MoveNext_InputArguments = 6052;

        /// <summary>
        /// The identifier for the OutputArguments Variable.
        /// </summary>
        public const uint PackMLStateModelType_MoveNext_OutputArguments = 6056;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint PackMLStateModelType_SetState_InputArguments = 6049;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_AddAlarm_InputArguments = 6062;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_AddAlarmsFromCSV_InputArguments = 6063;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_AddButtons_InputArguments = 6071;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_AddButtonsFromCSV_InputArguments = 6070;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_AddStackLight_InputArguments = 6066;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_AddStackLightsFromCSV_InputArguments = 6069;

        /// <summary>
        /// The identifier for the Alarms Variable.
        /// </summary>
        public const uint UnitType_Dictionnaries_Alarms = 6059;

        /// <summary>
        /// The identifier for the Buttons Variable.
        /// </summary>
        public const uint UnitType_Dictionnaries_Buttons = 6061;

        /// <summary>
        /// The identifier for the StackLights Variable.
        /// </summary>
        public const uint UnitType_Dictionnaries_StackLights = 6060;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_ExecuteProcess_InputArguments = 6082;

        /// <summary>
        /// The identifier for the MachineImage Variable.
        /// </summary>
        public const uint UnitType_MachineImage = 6010;

        /// <summary>
        /// The identifier for the MachineName Variable.
        /// </summary>
        public const uint UnitType_MachineName = 6001;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_ReadDataFromCSV_InputArguments = 6020;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_ReadDataFromDB_InputArguments = 6078;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_RemoveAlarm_InputArguments = 6074;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_RemoveButton_InputArguments = 6075;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_RemoveStackLight_InputArguments = 6076;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_SafeMoveNext_InputArguments = 6057;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_SaveDataToCSV_InputArguments = 6073;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_SaveDataToDB_InputArguments = 6077;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_SetMachineName_InputArguments = 6012;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_TriggerAlarm_InputArguments = 6064;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_TriggerButton_InputArguments = 6072;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_TriggerStackLight_InputArguments = 6067;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_UntriggerAlarm_InputArguments = 6065;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint UnitType_UntriggerStackLight_InputArguments = 6068;

        /// <summary>
        /// The identifier for the IsNamespaceSubset Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_PackMLModel__IsNamespaceSubset = 6013;

        /// <summary>
        /// The identifier for the NamespacePublicationDate Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_PackMLModel__NamespacePublicationDate = 6014;

        /// <summary>
        /// The identifier for the NamespaceUri Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_PackMLModel__NamespaceUri = 6015;

        /// <summary>
        /// The identifier for the NamespaceVersion Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_PackMLModel__NamespaceVersion = 6016;

        /// <summary>
        /// The identifier for the StaticNodeIdTypes Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_PackMLModel__StaticNodeIdTypes = 6017;

        /// <summary>
        /// The identifier for the StaticNumericNodeIdRange Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_PackMLModel__StaticNumericNodeIdRange = 6018;

        /// <summary>
        /// The identifier for the StaticStringNodeIdPattern Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_PackMLModel__StaticStringNodeIdPattern = 6019;

    }
    #endregion

    #region VariableTypes Identifiers
    /// <summary>
    /// A class that declares constants for all VariableTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class VariableTypes
    {
    }
    #endregion

    #region DataType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all DataTypes in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class DataTypeIds
    {
        /// <summary>
        /// The identifier for the AlarmType DataType.
        /// </summary>
        public static readonly ExpandedNodeId AlarmType = new ExpandedNodeId(DataTypes.AlarmType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the ButtonType DataType.
        /// </summary>
        public static readonly ExpandedNodeId ButtonType = new ExpandedNodeId(DataTypes.ButtonType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the ProcessType DataType.
        /// </summary>
        public static readonly ExpandedNodeId ProcessType = new ExpandedNodeId(DataTypes.ProcessType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the StackLightType DataType.
        /// </summary>
        public static readonly ExpandedNodeId StackLightType = new ExpandedNodeId(DataTypes.StackLightType, Namespaces.PackMLStateMachine);

    }
    #endregion

    #region Method Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Methods in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class MethodIds
    {
        /// <summary>
        /// The identifier for the PackMLStateModelType_GetAvailableCommands Method.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_GetAvailableCommands = new ExpandedNodeId(Methods.PackMLStateModelType_GetAvailableCommands, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_GetNext Method.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_GetNext = new ExpandedNodeId(Methods.PackMLStateModelType_GetNext, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_IsCommandAvailable Method.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_IsCommandAvailable = new ExpandedNodeId(Methods.PackMLStateModelType_IsCommandAvailable, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_MoveNext Method.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_MoveNext = new ExpandedNodeId(Methods.PackMLStateModelType_MoveNext, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_SetState Method.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_SetState = new ExpandedNodeId(Methods.PackMLStateModelType_SetState, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddAlarm Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddAlarm = new ExpandedNodeId(Methods.UnitType_AddAlarm, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddAlarmsFromCSV Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddAlarmsFromCSV = new ExpandedNodeId(Methods.UnitType_AddAlarmsFromCSV, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddButtons Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddButtons = new ExpandedNodeId(Methods.UnitType_AddButtons, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddButtonsFromCSV Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddButtonsFromCSV = new ExpandedNodeId(Methods.UnitType_AddButtonsFromCSV, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddStackLight Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddStackLight = new ExpandedNodeId(Methods.UnitType_AddStackLight, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddStackLightsFromCSV Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddStackLightsFromCSV = new ExpandedNodeId(Methods.UnitType_AddStackLightsFromCSV, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_ExecuteProcess Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_ExecuteProcess = new ExpandedNodeId(Methods.UnitType_ExecuteProcess, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_ReadDataFromCSV Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_ReadDataFromCSV = new ExpandedNodeId(Methods.UnitType_ReadDataFromCSV, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_ReadDataFromDB Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_ReadDataFromDB = new ExpandedNodeId(Methods.UnitType_ReadDataFromDB, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_RemoveAlarm Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_RemoveAlarm = new ExpandedNodeId(Methods.UnitType_RemoveAlarm, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_RemoveButton Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_RemoveButton = new ExpandedNodeId(Methods.UnitType_RemoveButton, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_RemoveStackLight Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_RemoveStackLight = new ExpandedNodeId(Methods.UnitType_RemoveStackLight, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_SafeMoveNext Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_SafeMoveNext = new ExpandedNodeId(Methods.UnitType_SafeMoveNext, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_SaveDataToCSV Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_SaveDataToCSV = new ExpandedNodeId(Methods.UnitType_SaveDataToCSV, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_SaveDataToDB Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_SaveDataToDB = new ExpandedNodeId(Methods.UnitType_SaveDataToDB, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_SetMachineName Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_SetMachineName = new ExpandedNodeId(Methods.UnitType_SetMachineName, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_TriggerAlarm Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_TriggerAlarm = new ExpandedNodeId(Methods.UnitType_TriggerAlarm, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_TriggerButton Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_TriggerButton = new ExpandedNodeId(Methods.UnitType_TriggerButton, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_TriggerStackLight Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_TriggerStackLight = new ExpandedNodeId(Methods.UnitType_TriggerStackLight, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_UntriggerAlarm Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_UntriggerAlarm = new ExpandedNodeId(Methods.UnitType_UntriggerAlarm, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_UntriggerStackLight Method.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_UntriggerStackLight = new ExpandedNodeId(Methods.UnitType_UntriggerStackLight, Namespaces.PackMLStateMachine);

    }
    #endregion

    #region Object Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class ObjectIds
    {
        /// <summary>
        /// The identifier for the UnitType_Dictionnaries Object.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_Dictionnaries = new ExpandedNodeId(Objects.UnitType_Dictionnaries, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the AlarmType_Encoding_DefaultBinary Object.
        /// </summary>
        public static readonly ExpandedNodeId AlarmType_Encoding_DefaultBinary = new ExpandedNodeId(Objects.AlarmType_Encoding_DefaultBinary, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the AlarmType_Encoding_DefaultJson Object.
        /// </summary>
        public static readonly ExpandedNodeId AlarmType_Encoding_DefaultJson = new ExpandedNodeId(Objects.AlarmType_Encoding_DefaultJson, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the AlarmType_Encoding_DefaultXml Object.
        /// </summary>
        public static readonly ExpandedNodeId AlarmType_Encoding_DefaultXml = new ExpandedNodeId(Objects.AlarmType_Encoding_DefaultXml, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the ButtonType_Encoding_DefaultBinary Object.
        /// </summary>
        public static readonly ExpandedNodeId ButtonType_Encoding_DefaultBinary = new ExpandedNodeId(Objects.ButtonType_Encoding_DefaultBinary, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the ButtonType_Encoding_DefaultJson Object.
        /// </summary>
        public static readonly ExpandedNodeId ButtonType_Encoding_DefaultJson = new ExpandedNodeId(Objects.ButtonType_Encoding_DefaultJson, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the ButtonType_Encoding_DefaultXml Object.
        /// </summary>
        public static readonly ExpandedNodeId ButtonType_Encoding_DefaultXml = new ExpandedNodeId(Objects.ButtonType_Encoding_DefaultXml, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the ProcessType_Encoding_DefaultBinary Object.
        /// </summary>
        public static readonly ExpandedNodeId ProcessType_Encoding_DefaultBinary = new ExpandedNodeId(Objects.ProcessType_Encoding_DefaultBinary, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the ProcessType_Encoding_DefaultJson Object.
        /// </summary>
        public static readonly ExpandedNodeId ProcessType_Encoding_DefaultJson = new ExpandedNodeId(Objects.ProcessType_Encoding_DefaultJson, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the ProcessType_Encoding_DefaultXml Object.
        /// </summary>
        public static readonly ExpandedNodeId ProcessType_Encoding_DefaultXml = new ExpandedNodeId(Objects.ProcessType_Encoding_DefaultXml, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the StackLightType_Encoding_DefaultBinary Object.
        /// </summary>
        public static readonly ExpandedNodeId StackLightType_Encoding_DefaultBinary = new ExpandedNodeId(Objects.StackLightType_Encoding_DefaultBinary, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the StackLightType_Encoding_DefaultJson Object.
        /// </summary>
        public static readonly ExpandedNodeId StackLightType_Encoding_DefaultJson = new ExpandedNodeId(Objects.StackLightType_Encoding_DefaultJson, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the StackLightType_Encoding_DefaultXml Object.
        /// </summary>
        public static readonly ExpandedNodeId StackLightType_Encoding_DefaultXml = new ExpandedNodeId(Objects.StackLightType_Encoding_DefaultXml, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_PackMLModel_ Object.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_PackMLModel_ = new ExpandedNodeId(Objects.Namespaces_http___yourorganisation_org_PackMLModel_, Namespaces.PackMLStateMachine);

    }
    #endregion

    #region ObjectType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class ObjectTypeIds
    {
        /// <summary>
        /// The identifier for the PackMLStateModelType ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType = new ExpandedNodeId(ObjectTypes.PackMLStateModelType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId UnitType = new ExpandedNodeId(ObjectTypes.UnitType, Namespaces.PackMLStateMachine);

    }
    #endregion

    #region ReferenceType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all ReferenceTypes in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class ReferenceTypeIds
    {
    }
    #endregion

    #region Variable Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Variables in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class VariableIds
    {
        /// <summary>
        /// The identifier for the OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema Variable.
        /// </summary>
        public static readonly ExpandedNodeId OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema = new ExpandedNodeId(Variables.OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_AlarmType Variable.
        /// </summary>
        public static readonly ExpandedNodeId OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_AlarmType = new ExpandedNodeId(Variables.OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_AlarmType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_ButtonType Variable.
        /// </summary>
        public static readonly ExpandedNodeId OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_ButtonType = new ExpandedNodeId(Variables.OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_ButtonType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_NamespaceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_NamespaceUri = new ExpandedNodeId(Variables.OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_NamespaceUri, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_ProcessType Variable.
        /// </summary>
        public static readonly ExpandedNodeId OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_ProcessType = new ExpandedNodeId(Variables.OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_ProcessType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_StackLightType Variable.
        /// </summary>
        public static readonly ExpandedNodeId OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_StackLightType = new ExpandedNodeId(Variables.OPCBinarySchema_TypeSystem_PackMLStateMachine_BinarySchema_StackLightType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema Variable.
        /// </summary>
        public static readonly ExpandedNodeId XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema = new ExpandedNodeId(Variables.XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_AlarmType Variable.
        /// </summary>
        public static readonly ExpandedNodeId XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_AlarmType = new ExpandedNodeId(Variables.XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_AlarmType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_ButtonType Variable.
        /// </summary>
        public static readonly ExpandedNodeId XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_ButtonType = new ExpandedNodeId(Variables.XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_ButtonType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_NamespaceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_NamespaceUri = new ExpandedNodeId(Variables.XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_NamespaceUri, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_ProcessType Variable.
        /// </summary>
        public static readonly ExpandedNodeId XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_ProcessType = new ExpandedNodeId(Variables.XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_ProcessType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_StackLightType Variable.
        /// </summary>
        public static readonly ExpandedNodeId XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_StackLightType = new ExpandedNodeId(Variables.XmlSchema_TypeSystem_PackMLStateMachine_XmlSchema_StackLightType, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_CurrentState Variable.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_CurrentState = new ExpandedNodeId(Variables.PackMLStateModelType_CurrentState, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_GetAvailableCommands_OutputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_GetAvailableCommands_OutputArguments = new ExpandedNodeId(Variables.PackMLStateModelType_GetAvailableCommands_OutputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_GetNext_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_GetNext_InputArguments = new ExpandedNodeId(Variables.PackMLStateModelType_GetNext_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_GetNext_OutputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_GetNext_OutputArguments = new ExpandedNodeId(Variables.PackMLStateModelType_GetNext_OutputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_IsCommandAvailable_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_IsCommandAvailable_InputArguments = new ExpandedNodeId(Variables.PackMLStateModelType_IsCommandAvailable_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_IsCommandAvailable_OutputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_IsCommandAvailable_OutputArguments = new ExpandedNodeId(Variables.PackMLStateModelType_IsCommandAvailable_OutputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_MoveNext_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_MoveNext_InputArguments = new ExpandedNodeId(Variables.PackMLStateModelType_MoveNext_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_MoveNext_OutputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_MoveNext_OutputArguments = new ExpandedNodeId(Variables.PackMLStateModelType_MoveNext_OutputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the PackMLStateModelType_SetState_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId PackMLStateModelType_SetState_InputArguments = new ExpandedNodeId(Variables.PackMLStateModelType_SetState_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddAlarm_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddAlarm_InputArguments = new ExpandedNodeId(Variables.UnitType_AddAlarm_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddAlarmsFromCSV_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddAlarmsFromCSV_InputArguments = new ExpandedNodeId(Variables.UnitType_AddAlarmsFromCSV_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddButtons_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddButtons_InputArguments = new ExpandedNodeId(Variables.UnitType_AddButtons_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddButtonsFromCSV_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddButtonsFromCSV_InputArguments = new ExpandedNodeId(Variables.UnitType_AddButtonsFromCSV_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddStackLight_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddStackLight_InputArguments = new ExpandedNodeId(Variables.UnitType_AddStackLight_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_AddStackLightsFromCSV_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_AddStackLightsFromCSV_InputArguments = new ExpandedNodeId(Variables.UnitType_AddStackLightsFromCSV_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_Dictionnaries_Alarms Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_Dictionnaries_Alarms = new ExpandedNodeId(Variables.UnitType_Dictionnaries_Alarms, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_Dictionnaries_Buttons Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_Dictionnaries_Buttons = new ExpandedNodeId(Variables.UnitType_Dictionnaries_Buttons, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_Dictionnaries_StackLights Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_Dictionnaries_StackLights = new ExpandedNodeId(Variables.UnitType_Dictionnaries_StackLights, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_ExecuteProcess_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_ExecuteProcess_InputArguments = new ExpandedNodeId(Variables.UnitType_ExecuteProcess_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_MachineImage Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_MachineImage = new ExpandedNodeId(Variables.UnitType_MachineImage, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_MachineName Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_MachineName = new ExpandedNodeId(Variables.UnitType_MachineName, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_ReadDataFromCSV_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_ReadDataFromCSV_InputArguments = new ExpandedNodeId(Variables.UnitType_ReadDataFromCSV_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_ReadDataFromDB_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_ReadDataFromDB_InputArguments = new ExpandedNodeId(Variables.UnitType_ReadDataFromDB_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_RemoveAlarm_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_RemoveAlarm_InputArguments = new ExpandedNodeId(Variables.UnitType_RemoveAlarm_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_RemoveButton_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_RemoveButton_InputArguments = new ExpandedNodeId(Variables.UnitType_RemoveButton_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_RemoveStackLight_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_RemoveStackLight_InputArguments = new ExpandedNodeId(Variables.UnitType_RemoveStackLight_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_SafeMoveNext_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_SafeMoveNext_InputArguments = new ExpandedNodeId(Variables.UnitType_SafeMoveNext_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_SaveDataToCSV_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_SaveDataToCSV_InputArguments = new ExpandedNodeId(Variables.UnitType_SaveDataToCSV_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_SaveDataToDB_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_SaveDataToDB_InputArguments = new ExpandedNodeId(Variables.UnitType_SaveDataToDB_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_SetMachineName_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_SetMachineName_InputArguments = new ExpandedNodeId(Variables.UnitType_SetMachineName_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_TriggerAlarm_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_TriggerAlarm_InputArguments = new ExpandedNodeId(Variables.UnitType_TriggerAlarm_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_TriggerButton_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_TriggerButton_InputArguments = new ExpandedNodeId(Variables.UnitType_TriggerButton_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_TriggerStackLight_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_TriggerStackLight_InputArguments = new ExpandedNodeId(Variables.UnitType_TriggerStackLight_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_UntriggerAlarm_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_UntriggerAlarm_InputArguments = new ExpandedNodeId(Variables.UnitType_UntriggerAlarm_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the UnitType_UntriggerStackLight_InputArguments Variable.
        /// </summary>
        public static readonly ExpandedNodeId UnitType_UntriggerStackLight_InputArguments = new ExpandedNodeId(Variables.UnitType_UntriggerStackLight_InputArguments, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_PackMLModel__IsNamespaceSubset Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_PackMLModel__IsNamespaceSubset = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_PackMLModel__IsNamespaceSubset, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_PackMLModel__NamespacePublicationDate Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_PackMLModel__NamespacePublicationDate = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_PackMLModel__NamespacePublicationDate, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_PackMLModel__NamespaceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_PackMLModel__NamespaceUri = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_PackMLModel__NamespaceUri, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_PackMLModel__NamespaceVersion Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_PackMLModel__NamespaceVersion = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_PackMLModel__NamespaceVersion, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_PackMLModel__StaticNodeIdTypes Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_PackMLModel__StaticNodeIdTypes = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_PackMLModel__StaticNodeIdTypes, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_PackMLModel__StaticNumericNodeIdRange Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_PackMLModel__StaticNumericNodeIdRange = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_PackMLModel__StaticNumericNodeIdRange, Namespaces.PackMLStateMachine);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_PackMLModel__StaticStringNodeIdPattern Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_PackMLModel__StaticStringNodeIdPattern = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_PackMLModel__StaticStringNodeIdPattern, Namespaces.PackMLStateMachine);

    }
    #endregion

    #region VariableType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all VariableType in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.9")]
    public static partial class VariableTypeIds
    {
    }
    #endregion

    #region BrowseName Declarations
    /// <summary>
    /// Declares all of the BrowseNames used in the Model.
    /// </summary>
    public static partial class BrowseNames
    {
        /// <summary>
        /// The BrowseName for the AddAlarm component.
        /// </summary>
        public const string AddAlarm = "AddAlarm";
        /// <summary>
        /// The BrowseName for the AddAlarmsFromCSV component.
        /// </summary>
        public const string AddAlarmsFromCSV = "AddAlarmsFromCSV";
        /// <summary>
        /// The BrowseName for the AddButtons component.
        /// </summary>
        public const string AddButtons = "AddButtons";
        /// <summary>
        /// The BrowseName for the AddButtonsFromCSV component.
        /// </summary>
        public const string AddButtonsFromCSV = "AddButtonsFromCSV";
        /// <summary>
        /// The BrowseName for the AddStackLight component.
        /// </summary>
        public const string AddStackLight = "AddStackLight";
        /// <summary>
        /// The BrowseName for the AddStackLightsFromCSV component.
        /// </summary>
        public const string AddStackLightsFromCSV = "AddStackLightsFromCSV";
        /// <summary>
        /// The BrowseName for the AlarmType component.
        /// </summary>
        public const string AlarmType = "AlarmType";
        /// <summary>
        /// The BrowseName for the Alarms component.
        /// </summary>
        public const string Alarms = "Alarms";
        /// <summary>
        /// The BrowseName for the ButtonType component.
        /// </summary>
        public const string ButtonType = "ButtonType";
        /// <summary>
        /// The BrowseName for the Buttons component.
        /// </summary>
        public const string Buttons = "Buttons";
        /// <summary>
        /// The BrowseName for the CurrentState component.
        /// </summary>
        public const string CurrentState = "CurrentState";
        /// <summary>
        /// The BrowseName for the Dictionnaries component.
        /// </summary>
        public const string Dictionnaries = "Dictionnaries";
        /// <summary>
        /// The BrowseName for the ExecuteProcess component.
        /// </summary>
        public const string ExecuteProcess = "ExecuteProcess";
        /// <summary>
        /// The BrowseName for the GetAvailableCommands component.
        /// </summary>
        public const string GetAvailableCommands = "GetAvailableCommands";
        /// <summary>
        /// The BrowseName for the GetNext component.
        /// </summary>
        public const string GetNext = "GetNext";
        /// <summary>
        /// The BrowseName for the IsCommandAvailable component.
        /// </summary>
        public const string IsCommandAvailable = "IsCommandAvailable";
        /// <summary>
        /// The BrowseName for the MachineImage component.
        /// </summary>
        public const string MachineImage = "MachineImage";
        /// <summary>
        /// The BrowseName for the MachineName component.
        /// </summary>
        public const string MachineName = "MachineName";
        /// <summary>
        /// The BrowseName for the MoveNext component.
        /// </summary>
        public const string MoveNext = "MoveNext";
        /// <summary>
        /// The BrowseName for the PackMLStateMachine component.
        /// </summary>
        public const string PackMLStateMachine_XmlSchema = "PackMLStateMachine";
        /// <summary>
        /// The BrowseName for the PackMLStateModelType component.
        /// </summary>
        public const string PackMLStateModelType = "PackMLStateModelType";
        /// <summary>
        /// The BrowseName for the ProcessType component.
        /// </summary>
        public const string ProcessType = "ProcessType";
        /// <summary>
        /// The BrowseName for the ReadDataFromCSV component.
        /// </summary>
        public const string ReadDataFromCSV = "ReadDataFromCSV";
        /// <summary>
        /// The BrowseName for the ReadDataFromDB component.
        /// </summary>
        public const string ReadDataFromDB = "ReadDataFromDB";
        /// <summary>
        /// The BrowseName for the RemoveAlarm component.
        /// </summary>
        public const string RemoveAlarm = "RemoveAlarm";
        /// <summary>
        /// The BrowseName for the RemoveButton component.
        /// </summary>
        public const string RemoveButton = "RemoveButton";
        /// <summary>
        /// The BrowseName for the RemoveStackLight component.
        /// </summary>
        public const string RemoveStackLight = "RemoveStackLight";
        /// <summary>
        /// The BrowseName for the SafeMoveNext component.
        /// </summary>
        public const string SafeMoveNext = "SafeMoveNext";
        /// <summary>
        /// The BrowseName for the SaveDataToCSV component.
        /// </summary>
        public const string SaveDataToCSV = "SaveDataToCSV";
        /// <summary>
        /// The BrowseName for the SaveDataToDB component.
        /// </summary>
        public const string SaveDataToDB = "SaveDataToDB";
        /// <summary>
        /// The BrowseName for the SetMachineName component.
        /// </summary>
        public const string SetMachineName = "SetMachineName";
        /// <summary>
        /// The BrowseName for the SetState component.
        /// </summary>
        public const string SetState = "SetState";
        /// <summary>
        /// The BrowseName for the StackLightType component.
        /// </summary>
        public const string StackLightType = "StackLightType";
        /// <summary>
        /// The BrowseName for the StackLights component.
        /// </summary>
        public const string StackLights = "StackLights";
        /// <summary>
        /// The BrowseName for the TriggerAlarm component.
        /// </summary>
        public const string TriggerAlarm = "TriggerAlarm";
        /// <summary>
        /// The BrowseName for the TriggerButton component.
        /// </summary>
        public const string TriggerButton = "TriggerButton";
        /// <summary>
        /// The BrowseName for the TriggerStackLight component.
        /// </summary>
        public const string TriggerStackLight = "TriggerStackLight";
        /// <summary>
        /// The BrowseName for the UnitType component.
        /// </summary>
        public const string UnitType = "UnitType";
        /// <summary>
        /// The BrowseName for the UntriggerAlarm component.
        /// </summary>
        public const string UntriggerAlarm = "UntriggerAlarm";
        /// <summary>
        /// The BrowseName for the UntriggerStackLight component.
        /// </summary>
        public const string UntriggerStackLight = "UntriggerStackLight";
        /// <summary>
        /// The BrowseName for the http://yourorganisation.org/PackMLModel/ component.
        /// </summary>
        public const string http___yourorganisation_org_PackMLModel_ = "http://yourorganisation.org/PackMLModel/";
    }
    #endregion

    #region Namespace Declarations
    /// <summary>
    /// Defines constants for all namespaces referenced by the Model.
    /// </summary>
    public static partial class Namespaces
    {
        /// <summary>
        /// The URI for the OpcUa namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUa = "http://opcfoundation.org/UA/";

        /// <summary>
        /// The URI for the OpcUaXsd namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUaXsd = "http://opcfoundation.org/UA/2008/02/Types.xsd";

        /// <summary>
        /// The URI for the PackMLStateMachine namespace.
        /// </summary>
        public const string PackMLStateMachine = "http://yourorganisation.org/PackMLModel/";

        /// <summary>
        /// The URI for the PackMLStateMachineXsd namespace.
        /// </summary>
        public const string PackMLStateMachineXsd = "http://yourorganisation.org/PackMLModel/Types.xsd";
    }
    #endregion
}

